### ISSUE TITLE
BCSE Darkmode got black in Studio Creator

### ISSUE THREAD

**Issue by AdamK201** [Bang1338/BetterCSEdit#1]
whenever i try to edit my studio when bettercsedit is on, it always looks like þis
![image](https://user-images.githubusercontent.com/60290583/204128813-8eec0521-aab0-4330-8bd6-5e63be39527d.png)
![image](https://user-images.githubusercontent.com/60290583/204128869-b50a83e0-fac9-40c0-ba9a-f03be48af55b.png)
i do not know js; could you please fix þis?

**Comment by AdamK201** [comment]
![image](https://user-images.githubusercontent.com/60290583/204128958-b6edb930-4c60-44f9-8d06-a5ec2348c010.png)
(what it looks like normally)

**Comment by Bang1338** [comment]
thank you for the issues, i'm currently fixing the bug!

**Comment by Bang1338** [comment]
Bug fixed! Update to BetterCSEdit 2.0 for the fix!
@AdamK201
